/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIApp1;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.io.*;
import java.util.*;
import gnu.io.*;
import java.math.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amit Bhargava
 */
public class GUIApp1 extends javax.swing.JFrame{
    CommPortIdentifier portId;
    CommPort port;
    public static SerialPort serialport;
    public static OutputStream outputstream;
    public static InputStream inputstream;
    final static int SPACE_ASCII = 32;
    final static int DASH_ASCII = 45;
    final static int NEW_LINE_ASCII = 10;
    int count=0; // used to set values of labels giving readings of sensors
    int status=0; // buzzer on: status=0, buzzer off: status=1
    int value, value1;
    float value2;
    Canvas canvas;
    //Thread readThread;

    /**
     * Creates new form GUIApp1
     */
    public GUIApp1() {
        initComponents();
        jComboBoxCOMPorts.removeAllItems();
        listSerialPorts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelCOMPort = new javax.swing.JPanel();
        jLabelCOMPort = new javax.swing.JLabel();
        jComboBoxCOMPorts = new javax.swing.JComboBox();
        jButtonCOMConnect = new javax.swing.JButton();
        jButtonCOMExit = new javax.swing.JButton();
        jLabelHeading = new javax.swing.JLabel();
        jPanelBuzzer = new javax.swing.JPanel();
        jLabelBuzzer = new javax.swing.JLabel();
        jButtonBuzzer = new javax.swing.JButton();
        jPanelMotionControl = new javax.swing.JPanel();
        jLabelMotionControl = new javax.swing.JLabel();
        jButtonStopMotion = new javax.swing.JButton();
        jButtonBackwardMotion = new javax.swing.JButton();
        jButtonRightMotion = new javax.swing.JButton();
        jButtonLeftMotion = new javax.swing.JButton();
        jButtonForwardMotion = new javax.swing.JButton();
        jPanelWLSensor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelRightWLSensor = new javax.swing.JLabel();
        jLabelCenterWLSensor = new javax.swing.JLabel();
        jLabelLeftWLSensor = new javax.swing.JLabel();
        canvas2 = new java.awt.Canvas();
        canvas1 = new java.awt.Canvas();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelVoltage = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelIRSensor1 = new javax.swing.JLabel();
        jLabelIRSensor2 = new javax.swing.JLabel();
        jLabelIRSensor3 = new javax.swing.JLabel();
        jLabelIRSensor4 = new javax.swing.JLabel();
        jLabelIRSensor5 = new javax.swing.JLabel();
        jLabelIRSensor6 = new javax.swing.JLabel();
        jLabelIRSensor7 = new javax.swing.JLabel();
        jLabelIRSensor8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabelSharpSensor3 = new javax.swing.JLabel();
        jLabelSharpSensor1 = new javax.swing.JLabel();
        jLabelSharpSensor2 = new javax.swing.JLabel();
        jLabelSharpSensor4 = new javax.swing.JLabel();
        jLabelSharpSensor5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1372, 750));

        jPanelFrame.setBackground(new java.awt.Color(204, 204, 255));

        jPanelCOMPort.setBackground(new java.awt.Color(153, 204, 255));
        jPanelCOMPort.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCOMPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCOMPort.setForeground(new java.awt.Color(0, 0, 102));
        jLabelCOMPort.setText("   COM PORT");

        jComboBoxCOMPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCOMPortsActionPerformed(evt);
            }
        });

        jButtonCOMConnect.setText("Connect");
        jButtonCOMConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMConnectActionPerformed(evt);
            }
        });

        jButtonCOMExit.setText("Exit");
        jButtonCOMExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCOMPortLayout = new javax.swing.GroupLayout(jPanelCOMPort);
        jPanelCOMPort.setLayout(jPanelCOMPortLayout);
        jPanelCOMPortLayout.setHorizontalGroup(
            jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCOMPorts, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCOMExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCOMConnect))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addComponent(jLabelCOMPort, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCOMPortLayout.setVerticalGroup(
            jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelCOMPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCOMPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCOMConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCOMExit)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHeading.setText("FIREBIRD V ATMEGA 2560");

        jPanelBuzzer.setBackground(new java.awt.Color(153, 204, 255));
        jPanelBuzzer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelBuzzer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBuzzer.setForeground(new java.awt.Color(0, 0, 102));
        jLabelBuzzer.setText("  BUZZER");

        jButtonBuzzer.setText("On");
        jButtonBuzzer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuzzerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuzzerLayout = new javax.swing.GroupLayout(jPanelBuzzer);
        jPanelBuzzer.setLayout(jPanelBuzzerLayout);
        jPanelBuzzerLayout.setHorizontalGroup(
            jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuzzerLayout.createSequentialGroup()
                .addComponent(jLabelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuzzerLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jButtonBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBuzzerLayout.setVerticalGroup(
            jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuzzerLayout.createSequentialGroup()
                .addComponent(jLabelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMotionControl.setBackground(new java.awt.Color(153, 204, 255));
        jPanelMotionControl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMotionControl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMotionControl.setForeground(new java.awt.Color(0, 0, 102));
        jLabelMotionControl.setText("MOTION CONTROL");

        jButtonStopMotion.setText("Stop");
        jButtonStopMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopMotionActionPerformed(evt);
            }
        });

        jButtonBackwardMotion.setText("Backward");
        jButtonBackwardMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackwardMotionActionPerformed(evt);
            }
        });

        jButtonRightMotion.setText("Right");
        jButtonRightMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightMotionActionPerformed(evt);
            }
        });

        jButtonLeftMotion.setText("Left");
        jButtonLeftMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftMotionActionPerformed(evt);
            }
        });

        jButtonForwardMotion.setText("Forward");
        jButtonForwardMotion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonForwardMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardMotionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotionControlLayout = new javax.swing.GroupLayout(jPanelMotionControl);
        jPanelMotionControl.setLayout(jPanelMotionControlLayout);
        jPanelMotionControlLayout.setHorizontalGroup(
            jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLeftMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMotionControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonStopMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBackwardMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRightMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonForwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanelMotionControlLayout.setVerticalGroup(
            jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addComponent(jLabelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMotionControlLayout.createSequentialGroup()
                        .addComponent(jButtonForwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLeftMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRightMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStopMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBackwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jPanelWLSensor.setBackground(new java.awt.Color(153, 204, 255));
        jPanelWLSensor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WHITE LINE SENSORS");

        jLabelRightWLSensor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRightWLSensor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCenterWLSensor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelLeftWLSensor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        canvas2.setBackground(new java.awt.Color(255, 255, 255));

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelWLSensorLayout = new javax.swing.GroupLayout(jPanelWLSensor);
        jPanelWLSensor.setLayout(jPanelWLSensorLayout);
        jPanelWLSensorLayout.setHorizontalGroup(
            jPanelWLSensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                .addGroup(jPanelWLSensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                        .addGroup(jPanelWLSensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelLeftWLSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCenterWLSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRightWLSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWLSensorLayout.setVerticalGroup(
            jPanelWLSensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelWLSensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCenterWLSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWLSensorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelWLSensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLeftWLSensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRightWLSensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIApp1/logo1.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("SERVO MOTOR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("   INTEGRATED WEBCAM");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText(" VELOCITY OF MOTORS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("VOLTAGE");

        jLabelVoltage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelVoltage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("   IR SENSORS READINGS");

        jLabelIRSensor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIRSensor8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelIRSensor1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIRSensor2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIRSensor3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIRSensor4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIRSensor5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIRSensor6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIRSensor7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIRSensor8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIRSensor1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRSensor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("DISTANCE SENSORS");

        jLabelSharpSensor3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSharpSensor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSharpSensor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSharpSensor4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelSharpSensor5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabelSharpSensor1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSharpSensor2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSharpSensor3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSharpSensor4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSharpSensor5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSharpSensor5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelSharpSensor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSharpSensor3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelSharpSensor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSharpSensor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanelFrameLayout = new javax.swing.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFrameLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                        .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(420, 420, 420))
                    .addGroup(jPanelFrameLayout.createSequentialGroup()
                        .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelFrameLayout.createSequentialGroup()
                                .addComponent(jPanelCOMPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelBuzzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelMotionControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelWLSensor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFrameLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFrameLayout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFrameLayout.createSequentialGroup()
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFrameLayout.createSequentialGroup()
                        .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCOMPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBuzzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelWLSensor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuzzerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuzzerActionPerformed
        if(status==0){
            writeOnTerminal("7");
            status=1;
            jButtonBuzzer.setText("Off");
        }
        else if(status==1){
            writeOnTerminal("9");
            status=0;
            jButtonBuzzer.setText("On");
        }
    }//GEN-LAST:event_jButtonBuzzerActionPerformed

    private void jButtonForwardMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardMotionActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Forward");
        writeOnTerminal("8");
    }//GEN-LAST:event_jButtonForwardMotionActionPerformed

    private void jButtonRightMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightMotionActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Right");
        writeOnTerminal("6");
    }//GEN-LAST:event_jButtonRightMotionActionPerformed

    private void jButtonBackwardMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackwardMotionActionPerformed
       //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Backward");
        writeOnTerminal("2");
    }//GEN-LAST:event_jButtonBackwardMotionActionPerformed

    private void jButtonLeftMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftMotionActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Left");
        writeOnTerminal("4");
    }//GEN-LAST:event_jButtonLeftMotionActionPerformed

    private void jButtonStopMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopMotionActionPerformed
         //JOptionPane.showMessageDialog(jPanelFrame,"Bot stops");
        writeOnTerminal("5");
    }//GEN-LAST:event_jButtonStopMotionActionPerformed

    private void jButtonCOMConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMConnectActionPerformed
        // TODO add your handling code here:
        String selectedPort = (String)jComboBoxCOMPorts.getSelectedItem();
        Connect(selectedPort);
        new Thread(new ReadThread()).start();
    }//GEN-LAST:event_jButtonCOMConnectActionPerformed

    private void jButtonCOMExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMExitActionPerformed
        // TODO add your handling code here:
        removeSerialPorts();
    }//GEN-LAST:event_jButtonCOMExitActionPerformed

    private void jComboBoxCOMPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCOMPortsActionPerformed
        // TODO add your handling code here:
        
        //JOptionPane.showMessageDialog(jPanelFrame, selectedPort);
    }//GEN-LAST:event_jComboBoxCOMPortsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //SerialCommunication1 serialcomm1 = new SerialCommunication1();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIApp1().setVisible(true);
            }
        });
    }
    
    
    
    private void listSerialPorts() {   // Function to lis the available COM ports in jComboBox
    Enumeration ports = CommPortIdentifier.getPortIdentifiers();
    ArrayList portList = new ArrayList();
    String portArray[] = null;
    while (ports.hasMoreElements()) {
        CommPortIdentifier portIdentified = (CommPortIdentifier) ports.nextElement();
        if (portIdentified.getPortType() == CommPortIdentifier.PORT_SERIAL) {
            portList.add(portIdentified.getName());
        }
    }
    portArray = (String[]) portList.toArray(new String[0]);
    //return portArray;
    jComboBoxCOMPorts.setModel(new javax.swing.DefaultComboBoxModel(portArray));
    jComboBoxCOMPorts.setSelectedIndex(-1);
}
    
    public void removeSerialPorts(){    // Function to disconnect to the serial port
        try {
            //jComboBoxCOMPorts.removeAllItems();
            serialport.close();
            jLabelRightWLSensor.setText(null);
            jLabelCenterWLSensor.setText(null);
            jLabelLeftWLSensor.setText(null);
            jLabelIRSensor1.setText(null);
            jLabelIRSensor2.setText(null);
            jLabelIRSensor3.setText(null);
            jLabelIRSensor4.setText(null);
            jLabelIRSensor5.setText(null);
            jLabelIRSensor6.setText(null);
            jLabelIRSensor7.setText(null);
            jLabelIRSensor8.setText(null);
            jLabelSharpSensor1.setText(null);
            jLabelSharpSensor2.setText(null);
            jLabelSharpSensor3.setText(null);
            jLabelSharpSensor4.setText(null);
            jLabelSharpSensor5.setText(null);
            jLabelVoltage.setText(null);
            outputstream.close();
            inputstream.close();
        } catch (IOException ex) {
            Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void writeOnTerminal(String serialmessage){  // Function to write on the serial port
        try {
            outputstream.write(serialmessage.getBytes());
            outputstream.flush();
        } catch (IOException ex) {
            Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println("written on serialport");
    }
    
    
    private class ReadThread implements Runnable {  // Thread to read the value of sensors
    public void run() {
        while(portId.isCurrentlyOwned()) {
            try {
                Thread.sleep(10);
                writeOnTerminal("A");
                count=1;
                Thread.sleep(60);
                writeOnTerminal("B");
                count=2;
                Thread.sleep(60);
                writeOnTerminal("C");
                count=3;
                Thread.sleep(60);
                writeOnTerminal("D");
                count=4;
                Thread.sleep(60);
                writeOnTerminal("E");
                count=5;
                Thread.sleep(60);
                writeOnTerminal("F");
                count=6;
                Thread.sleep(60);
                writeOnTerminal("G");
                count=7;
                Thread.sleep(60);
                writeOnTerminal("H");
                count=8;
                Thread.sleep(60);
                writeOnTerminal("I");
                count=9;
                Thread.sleep(60);
                writeOnTerminal("J");
                count=10;
                Thread.sleep(60);
                writeOnTerminal("K");
                count=11;
                Thread.sleep(60);
                writeOnTerminal("L");
                count=12;
                Thread.sleep(60);
                writeOnTerminal("M");
                count=13;
                Thread.sleep(60);
                writeOnTerminal("N");
                count=14;
                Thread.sleep(60);
                writeOnTerminal("O");
                count=15;
                Thread.sleep(60);
                writeOnTerminal("P");
                count=16;
                Thread.sleep(60);
                writeOnTerminal("Q");
                count=17;
                Thread.sleep(60);
            } catch (InterruptedException ex) {
                Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
    
    public void Connect(String portName){  // Function to connect to the serial port
        try {
            System.out.println("Connect to Port");
            portId = CommPortIdentifier.getPortIdentifier(portName);
            System.out.println(portId.getName());
            try {
                port = portId.open("Demo Application", 5000);
                System.out.println("Get the port's ownership");
                //port.close();
                serialport = (SerialPort)port;
                int baudRate = 115200;
                try {
                    serialport.setSerialPortParams(
                            baudRate,
                            SerialPort.DATABITS_8,
                            SerialPort.STOPBITS_1,
                            SerialPort.PARITY_NONE);
                    serialport.setFlowControlMode(SerialPort.FLOWCONTROL_NONE);
                    System.out.println("Parameters set");
                    SetInputOutputStream();
                    setSerialEventHandler();
 
                  } catch (UnsupportedCommOperationException ex) {
                    //Logger.getLogger(SerialCommunication.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("UnsupportedCommOperationException");
                }
            } catch (PortInUseException ex) {
                //Logger.getLogger(SerialCommunication.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("PortInUseException");
            }
            
        } catch (NoSuchPortException ex) {
            //Logger.getLogger(SerialCommunication.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("NoSuchPortException");
        }
        
        
        //System.out.println(portId);
        
       }
    
    public void SetInputOutputStream(){   // Function to set Input and Output Stream
        try {
            inputstream = serialport.getInputStream();
            outputstream = serialport.getOutputStream();
            System.out.println("Set Inputstrem and Outputstream");
        } catch (IOException ex) {
            Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private class SerialEventHandler1 implements SerialPortEventListener{

        @Override
        public void serialEvent(SerialPortEvent spe) {   // Method called when event to read from serial port occurs
            //byte[] readBuffer = new byte[400];
            System.out.println("Serial Event");
            switch(spe.getEventType()){
                case SerialPortEvent.DATA_AVAILABLE:
                    
                    //int availableBytes, len;
                    //int value; 
            try {
                byte singleData = (byte)inputstream.read();

                if (singleData != NEW_LINE_ASCII)
                {
                    //String logText = new String(new byte[] {singleData});
                    value= singleData & 0xff;
                    //System.out.println(value);
                    String input = new String();
                    input = String.valueOf(value);
                    //System.out.println(input);
                    if(count==1){
                        jLabelRightWLSensor.setText(input);
                    }
                    if(count==2){
                        jLabelCenterWLSensor.setText(input);
                    }
                    if(count==3){
                        jLabelLeftWLSensor.setText(input);
                    }
                    if(count==4){
                        jLabelIRSensor1.setText(input);
                    }
                    if(count==5){
                        jLabelIRSensor2.setText(input);
                    }
                    if(count==6){
                        jLabelIRSensor3.setText(input);
                    }
                    if(count==7){
                        jLabelIRSensor4.setText(input);
                    }
                    if(count==8){
                        jLabelIRSensor5.setText(input);
                    }
                    if(count==9){
                        jLabelIRSensor6.setText(input);
                    }
                    if(count==10){
                        jLabelIRSensor7.setText(input);
                    }
                    if(count==11){
                        jLabelIRSensor8.setText(input);
                    }
                    if (count==12){
                        value1= Sharp_GP2D12_estimation(value);
                        input = String.valueOf(value1);
                        jLabelSharpSensor1.setText(input+"mm");
                    }
                    if (count==13){
                        value1= Sharp_GP2D12_estimation(value);
                        input = String.valueOf(value1);
                        jLabelSharpSensor2.setText(input+"mm");
                    }
                    if (count==14){
                        value1= Sharp_GP2D12_estimation(value);
                        input = String.valueOf(value1);
                        jLabelSharpSensor3.setText(input+"mm");
                    }
                    if (count==15){
                        value1= Sharp_GP2D12_estimation(value);
                        input = String.valueOf(value1);
                        jLabelSharpSensor4.setText(input+"mm");
                    }
                    if (count==16){
                        value1= Sharp_GP2D12_estimation(value);
                        input = String.valueOf(value1);
                        jLabelSharpSensor5.setText(input+"mm");
                    }
                    if(count==17){
                        value2 = (float)(((((value)*100)*0.07902) + 0.7)/100);
                        input = String.valueOf(value2);
                        jLabelVoltage.setText("   "+input+"V");
                                
                    }
                }
                /*availableBytes = inputstream.available();
                System.out.println(availableBytes);
                    if(availableBytes>0){
                        inputstream.read(readBuffer, 0, availableBytes);
                        System.out.println(readBuffer);
                        //String input = new String(readBuffer, 0, availableBytes);
                        //System.out.println(Integer.decode(input));
                        //while (len!=-1){
                            
                        }*/
            }catch (IOException ex) {
                Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
    }
 }
        
    
  public void setSerialEventHandler(){   // Function to set Event Listener to read from the serial port
      SerialEventHandler1 seh1 = new SerialEventHandler1();
        try {
            serialport.addEventListener(seh1);
            serialport.notifyOnDataAvailable(true);
        } catch (TooManyListenersException ex) {
            Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  }
  
 int Sharp_GP2D12_estimation (int value){
     float distance;
	int distanceInt;
	distance = (int)(10.00*(2799.6*(1.00/(Math.pow(value,1.1546)))));
	distanceInt = (int)distance;
	if(distanceInt>800)
	{
		distanceInt=800;
	}
	return distanceInt;
     
 }
       


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Canvas canvas1;
    public java.awt.Canvas canvas2;
    public javax.swing.JButton jButtonBackwardMotion;
    private javax.swing.JButton jButtonBuzzer;
    public javax.swing.JButton jButtonCOMConnect;
    public javax.swing.JButton jButtonCOMExit;
    public javax.swing.JButton jButtonForwardMotion;
    public javax.swing.JButton jButtonLeftMotion;
    public javax.swing.JButton jButtonRightMotion;
    public javax.swing.JButton jButtonStopMotion;
    public javax.swing.JComboBox jComboBoxCOMPorts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBuzzer;
    private javax.swing.JLabel jLabelCOMPort;
    public javax.swing.JLabel jLabelCenterWLSensor;
    private javax.swing.JLabel jLabelHeading;
    public javax.swing.JLabel jLabelIRSensor1;
    public javax.swing.JLabel jLabelIRSensor2;
    public javax.swing.JLabel jLabelIRSensor3;
    public javax.swing.JLabel jLabelIRSensor4;
    public javax.swing.JLabel jLabelIRSensor5;
    public javax.swing.JLabel jLabelIRSensor6;
    public javax.swing.JLabel jLabelIRSensor7;
    public javax.swing.JLabel jLabelIRSensor8;
    public javax.swing.JLabel jLabelLeftWLSensor;
    private javax.swing.JLabel jLabelMotionControl;
    public javax.swing.JLabel jLabelRightWLSensor;
    public javax.swing.JLabel jLabelSharpSensor1;
    public javax.swing.JLabel jLabelSharpSensor2;
    public javax.swing.JLabel jLabelSharpSensor3;
    public javax.swing.JLabel jLabelSharpSensor4;
    public javax.swing.JLabel jLabelSharpSensor5;
    public javax.swing.JLabel jLabelVoltage;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBuzzer;
    private javax.swing.JPanel jPanelCOMPort;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelMotionControl;
    public javax.swing.JPanel jPanelWLSensor;
    // End of variables declaration//GEN-END:variables
}
