/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIApp1;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.io.*;
import java.util.*;
import gnu.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amit Bhargava
 */
public class GUIApp1 extends javax.swing.JFrame {
    CommPortIdentifier portId;
       CommPort port;
       public static SerialPort serialport;
       public static OutputStream outputstream;
       public static InputStream inputstream;

    /**
     * Creates new form GUIApp1
     */
    public GUIApp1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelCOMPort = new javax.swing.JPanel();
        jLabelCOMPort = new javax.swing.JLabel();
        jComboBoxCOMPorts = new javax.swing.JComboBox();
        jButtonCOMConnect = new javax.swing.JButton();
        jButtonCOMExit = new javax.swing.JButton();
        jLabelHeading = new javax.swing.JLabel();
        jPanelBuzzer = new javax.swing.JPanel();
        jLabelBuzzer = new javax.swing.JLabel();
        jButtonBuzzerOn = new javax.swing.JButton();
        jButtonBuzzerOff = new javax.swing.JButton();
        jPanelMotionControl = new javax.swing.JPanel();
        jLabelMotionControl = new javax.swing.JLabel();
        jButtonStopMotion = new javax.swing.JButton();
        jButtonBackwardMotion = new javax.swing.JButton();
        jButtonRightMotion = new javax.swing.JButton();
        jButtonLeftMotion = new javax.swing.JButton();
        jButtonForwardMotion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanelCOMPort.setBackground(new java.awt.Color(153, 204, 255));
        jPanelCOMPort.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCOMPort.setForeground(new java.awt.Color(0, 0, 102));
        jLabelCOMPort.setText("   COM PORT");

        jComboBoxCOMPorts.setEditable(true);
        jComboBoxCOMPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCOMPortsActionPerformed(evt);
            }
        });

        jButtonCOMConnect.setText("Connect");
        jButtonCOMConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMConnectActionPerformed(evt);
            }
        });

        jButtonCOMExit.setText("Exit");
        jButtonCOMExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCOMPortLayout = new javax.swing.GroupLayout(jPanelCOMPort);
        jPanelCOMPort.setLayout(jPanelCOMPortLayout);
        jPanelCOMPortLayout.setHorizontalGroup(
            jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCOMPort, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxCOMPorts, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCOMExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCOMConnect))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelCOMPortLayout.setVerticalGroup(
            jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelCOMPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCOMPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCOMPortLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCOMConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCOMExit)))
                .addContainerGap())
        );

        jLabelHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHeading.setText("FIREBIRD V ATMEGA 2560");

        jPanelBuzzer.setBackground(new java.awt.Color(153, 204, 255));
        jPanelBuzzer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelBuzzer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuzzer.setForeground(new java.awt.Color(0, 0, 102));
        jLabelBuzzer.setText("  BUZZER");

        jButtonBuzzerOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIApp1/button.jpg"))); // NOI18N
        jButtonBuzzerOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuzzerOnActionPerformed(evt);
            }
        });

        jButtonBuzzerOff.setText("Off");
        jButtonBuzzerOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuzzerOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuzzerLayout = new javax.swing.GroupLayout(jPanelBuzzer);
        jPanelBuzzer.setLayout(jPanelBuzzerLayout);
        jPanelBuzzerLayout.setHorizontalGroup(
            jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuzzerLayout.createSequentialGroup()
                .addComponent(jLabelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuzzerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBuzzerOff, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButtonBuzzerOn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBuzzerLayout.setVerticalGroup(
            jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuzzerLayout.createSequentialGroup()
                .addComponent(jLabelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuzzerOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuzzerOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanelMotionControl.setBackground(new java.awt.Color(153, 204, 255));
        jPanelMotionControl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMotionControl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMotionControl.setForeground(new java.awt.Color(0, 0, 102));
        jLabelMotionControl.setText("  Motion Control");

        jButtonStopMotion.setText("Stop");
        jButtonStopMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopMotionActionPerformed(evt);
            }
        });

        jButtonBackwardMotion.setText("Backward");
        jButtonBackwardMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackwardMotionActionPerformed(evt);
            }
        });

        jButtonRightMotion.setText("Right");
        jButtonRightMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightMotionActionPerformed(evt);
            }
        });

        jButtonLeftMotion.setText("Left");
        jButtonLeftMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftMotionActionPerformed(evt);
            }
        });

        jButtonForwardMotion.setText("Forward");
        jButtonForwardMotion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonForwardMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardMotionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotionControlLayout = new javax.swing.GroupLayout(jPanelMotionControl);
        jPanelMotionControl.setLayout(jPanelMotionControlLayout);
        jPanelMotionControlLayout.setHorizontalGroup(
            jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLeftMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonStopMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonForwardMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBackwardMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRightMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanelMotionControlLayout.setVerticalGroup(
            jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonForwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonStopMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLeftMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRightMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBackwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("WHITE LINE SENSORS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(canvas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFrameLayout = new javax.swing.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(491, 491, 491))
            .addGroup(jPanelFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFrameLayout.createSequentialGroup()
                        .addComponent(jPanelCOMPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelMotionControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFrameLayout.createSequentialGroup()
                .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCOMPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBuzzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuzzerOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuzzerOnActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Buzzer Beeps");
        writeOnTerminal("7");
    }//GEN-LAST:event_jButtonBuzzerOnActionPerformed

    private void jButtonForwardMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardMotionActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Forward");
        writeOnTerminal("8");
    }//GEN-LAST:event_jButtonForwardMotionActionPerformed

    private void jButtonRightMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightMotionActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Right");
        writeOnTerminal("6");
    }//GEN-LAST:event_jButtonRightMotionActionPerformed

    private void jButtonBackwardMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackwardMotionActionPerformed
       //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Backward");
        writeOnTerminal("2");
    }//GEN-LAST:event_jButtonBackwardMotionActionPerformed

    private void jButtonLeftMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftMotionActionPerformed
        //JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Left");
        writeOnTerminal("4");
    }//GEN-LAST:event_jButtonLeftMotionActionPerformed

    private void jButtonStopMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopMotionActionPerformed
         //JOptionPane.showMessageDialog(jPanelFrame,"Bot stops");
        writeOnTerminal("5");
    }//GEN-LAST:event_jButtonStopMotionActionPerformed

    private void jButtonCOMConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMConnectActionPerformed
        // TODO add your handling code here:
        listSerialPorts();
    }//GEN-LAST:event_jButtonCOMConnectActionPerformed

    private void jButtonCOMExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMExitActionPerformed
        // TODO add your handling code here:
        removeSerialPorts();
    }//GEN-LAST:event_jButtonCOMExitActionPerformed

    private void jComboBoxCOMPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCOMPortsActionPerformed
        // TODO add your handling code here:
        String selectedPort = (String)jComboBoxCOMPorts.getSelectedItem();
        Connect(selectedPort);
        //JOptionPane.showMessageDialog(jPanelFrame, selectedPort);
    }//GEN-LAST:event_jComboBoxCOMPortsActionPerformed

    private void jButtonBuzzerOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuzzerOffActionPerformed
        // TODO add your handling code here:
        writeOnTerminal("9");
    }//GEN-LAST:event_jButtonBuzzerOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIApp1().setVisible(true);
            }
        });
    }
    
    public void /*static String[]*/ listSerialPorts() {
 
    Enumeration ports = CommPortIdentifier.getPortIdentifiers();
    ArrayList portList = new ArrayList();
    String portArray[] = null;
    while (ports.hasMoreElements()) {
        CommPortIdentifier portIdentified = (CommPortIdentifier) ports.nextElement();
        if (portIdentified.getPortType() == CommPortIdentifier.PORT_SERIAL) {
            portList.add(portIdentified.getName());
        }
    }
    portArray = (String[]) portList.toArray(new String[0]);
    //return portArray;
    jComboBoxCOMPorts.setModel(new javax.swing.DefaultComboBoxModel(portArray));
}
    
    public void removeSerialPorts(){
        jComboBoxCOMPorts.removeAllItems();
    }
    
    public void writeOnTerminal(String serialmessage){
        try {
            outputstream.write(serialmessage.getBytes());
        } catch (IOException ex) {
            Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("written on serialport");
    }
    
    public void Connect(String portName){
        try {
            System.out.println("Connect to Port");
            portId = CommPortIdentifier.getPortIdentifier(portName);
            System.out.println(portId.getName());
            try {
                port = portId.open("Demo Application", 5000);
                System.out.println("Get the port's ownership");
                //port.close();
                serialport = (SerialPort)port;
                int baudRate = 9600;
                try {
                    serialport.setSerialPortParams(
                            baudRate,
                            SerialPort.DATABITS_8,
                            SerialPort.STOPBITS_1,
                            SerialPort.PARITY_NONE);
                    serialport.setFlowControlMode(SerialPort.FLOWCONTROL_NONE);
                    System.out.println("Parameters set");
                    try {
                        inputstream = serialport.getInputStream();
                        outputstream = serialport.getOutputStream();
                        System.out.println("Set Inputstrem and Outputstream");
                    } catch (IOException ex) {
                        Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
 
                  } catch (UnsupportedCommOperationException ex) {
                    //Logger.getLogger(SerialCommunication.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("UnsupportedCommOperationException");
                }
            } catch (PortInUseException ex) {
                //Logger.getLogger(SerialCommunication.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("PortInUseException");
            }
            
        } catch (NoSuchPortException ex) {
            //Logger.getLogger(SerialCommunication.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("NoSuchPortException");
        }
        
        
        //System.out.println(portId);
        
       }
    
    /*public void SetInputOutputStream(){
        try {
            inputstream = serialport.getInputStream();
            outputstream = serialport.getOutputStream();
            System.out.println("Set Inputstrem and Outputstream");
        } catch (IOException ex) {
            Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    private class SerialEventHandler1 implements SerialPortEventListener{

        @Override
        public void serialEvent(SerialPortEvent spe) {
            byte[] readBuffer = new byte[400];
            System.out.println("Serial Event");
            switch(spe.getEventType()){
                case SerialPortEvent.DATA_AVAILABLE:
                    int availableBytes;
            try {
                availableBytes = inputstream.available();
                System.out.println(availableBytes);
                    if(availableBytes>0){
                        inputstream.read(readBuffer, 0, availableBytes);
                        System.out.println(new String(readBuffer, 0, availableBytes));
                }
            }catch (IOException ex) {
                Logger.getLogger(GUIApp1.class.getName()).log(Level.SEVERE, null, ex);
            }
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
    }
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    public javax.swing.JButton jButtonBackwardMotion;
    public javax.swing.JButton jButtonBuzzerOff;
    private javax.swing.JButton jButtonBuzzerOn;
    public javax.swing.JButton jButtonCOMConnect;
    public javax.swing.JButton jButtonCOMExit;
    public javax.swing.JButton jButtonForwardMotion;
    public javax.swing.JButton jButtonLeftMotion;
    public javax.swing.JButton jButtonRightMotion;
    public javax.swing.JButton jButtonStopMotion;
    public javax.swing.JComboBox jComboBoxCOMPorts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBuzzer;
    private javax.swing.JLabel jLabelCOMPort;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelMotionControl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBuzzer;
    private javax.swing.JPanel jPanelCOMPort;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelMotionControl;
    // End of variables declaration//GEN-END:variables
}
