/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIApp1;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Amit Bhargava
 */
public class GUIApp1 extends javax.swing.JFrame {

    /**
     * Creates new form GUIApp1
     */
    public GUIApp1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrame = new javax.swing.JPanel();
        jPanelCOMPort = new javax.swing.JPanel();
        jLabelCOMPort = new javax.swing.JLabel();
        COMports = new javax.swing.JComboBox();
        jButtonCOMConnect = new javax.swing.JButton();
        jButtonCOMExit = new javax.swing.JButton();
        jLabelHeading = new javax.swing.JLabel();
        jPanelBuzzer = new javax.swing.JPanel();
        jLabelBuzzer = new javax.swing.JLabel();
        jButtonBuzzer = new javax.swing.JButton();
        jPanelMotionControl = new javax.swing.JPanel();
        jLabelMotionControl = new javax.swing.JLabel();
        jButtonStopMotion = new javax.swing.JButton();
        jButtonBackwardMotion = new javax.swing.JButton();
        jButtonRightMotion = new javax.swing.JButton();
        jButtonLeftMotion = new javax.swing.JButton();
        jButtonForwardMotion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanelCOMPort.setBackground(new java.awt.Color(153, 204, 255));
        jPanelCOMPort.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCOMPort.setForeground(new java.awt.Color(0, 0, 102));
        jLabelCOMPort.setText("   COM PORT");

        COMports.setEditable(true);

        jButtonCOMConnect.setText("Connect");

        jButtonCOMExit.setText("Exit");

        javax.swing.GroupLayout jPanelCOMPortLayout = new javax.swing.GroupLayout(jPanelCOMPort);
        jPanelCOMPort.setLayout(jPanelCOMPortLayout);
        jPanelCOMPortLayout.setHorizontalGroup(
            jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCOMPort, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(COMports, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCOMExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCOMConnect))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelCOMPortLayout.setVerticalGroup(
            jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                .addGroup(jPanelCOMPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCOMPortLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelCOMPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(COMports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCOMPortLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCOMConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCOMExit)))
                .addContainerGap())
        );

        jLabelHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHeading.setText("FIREBIRD V ATMEGA 2560");

        jPanelBuzzer.setBackground(new java.awt.Color(153, 204, 255));
        jPanelBuzzer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelBuzzer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuzzer.setForeground(new java.awt.Color(0, 0, 102));
        jLabelBuzzer.setText("  BUZZER");

        jButtonBuzzer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIApp1/button.jpg"))); // NOI18N
        jButtonBuzzer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuzzerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuzzerLayout = new javax.swing.GroupLayout(jPanelBuzzer);
        jPanelBuzzer.setLayout(jPanelBuzzerLayout);
        jPanelBuzzerLayout.setHorizontalGroup(
            jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuzzerLayout.createSequentialGroup()
                .addComponent(jLabelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuzzerLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jButtonBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBuzzerLayout.setVerticalGroup(
            jPanelBuzzerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuzzerLayout.createSequentialGroup()
                .addComponent(jLabelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMotionControl.setBackground(new java.awt.Color(153, 204, 255));
        jPanelMotionControl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMotionControl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMotionControl.setForeground(new java.awt.Color(0, 0, 102));
        jLabelMotionControl.setText("  Motion Control");

        jButtonStopMotion.setText("Stop");
        jButtonStopMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopMotionActionPerformed(evt);
            }
        });

        jButtonBackwardMotion.setText("Backward");
        jButtonBackwardMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackwardMotionActionPerformed(evt);
            }
        });

        jButtonRightMotion.setText("Right");
        jButtonRightMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightMotionActionPerformed(evt);
            }
        });

        jButtonLeftMotion.setText("Left");
        jButtonLeftMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftMotionActionPerformed(evt);
            }
        });

        jButtonForwardMotion.setText("Forward");
        jButtonForwardMotion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonForwardMotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardMotionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotionControlLayout = new javax.swing.GroupLayout(jPanelMotionControl);
        jPanelMotionControl.setLayout(jPanelMotionControlLayout);
        jPanelMotionControlLayout.setHorizontalGroup(
            jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLeftMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonStopMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonForwardMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBackwardMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRightMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanelMotionControlLayout.setVerticalGroup(
            jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMotionControlLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonForwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMotionControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonStopMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLeftMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRightMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBackwardMotion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("   WHITE LINE SENSORS READINGS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFrameLayout = new javax.swing.GroupLayout(jPanelFrame);
        jPanelFrame.setLayout(jPanelFrameLayout);
        jPanelFrameLayout.setHorizontalGroup(
            jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFrameLayout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(491, 491, 491))
            .addGroup(jPanelFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFrameLayout.createSequentialGroup()
                        .addComponent(jPanelCOMPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMotionControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFrameLayout.setVerticalGroup(
            jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFrameLayout.createSequentialGroup()
                .addComponent(jLabelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCOMPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBuzzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMotionControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuzzerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuzzerActionPerformed
        JOptionPane.showMessageDialog(jPanelFrame,"Buzzer Beeps");
    }//GEN-LAST:event_jButtonBuzzerActionPerformed

    private void jButtonForwardMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardMotionActionPerformed
        JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Forward");
    }//GEN-LAST:event_jButtonForwardMotionActionPerformed

    private void jButtonRightMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightMotionActionPerformed
        JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Right");
    }//GEN-LAST:event_jButtonRightMotionActionPerformed

    private void jButtonBackwardMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackwardMotionActionPerformed
       JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Backward");
    }//GEN-LAST:event_jButtonBackwardMotionActionPerformed

    private void jButtonLeftMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftMotionActionPerformed
        JOptionPane.showMessageDialog(jPanelFrame,"Bot moves Left");
    }//GEN-LAST:event_jButtonLeftMotionActionPerformed

    private void jButtonStopMotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopMotionActionPerformed
         JOptionPane.showMessageDialog(jPanelFrame,"Bot stops");
    }//GEN-LAST:event_jButtonStopMotionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIApp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox COMports;
    private javax.swing.JButton jButtonBackwardMotion;
    private javax.swing.JButton jButtonBuzzer;
    private javax.swing.JButton jButtonCOMConnect;
    private javax.swing.JButton jButtonCOMExit;
    private javax.swing.JButton jButtonForwardMotion;
    private javax.swing.JButton jButtonLeftMotion;
    private javax.swing.JButton jButtonRightMotion;
    private javax.swing.JButton jButtonStopMotion;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBuzzer;
    private javax.swing.JLabel jLabelCOMPort;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelMotionControl;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBuzzer;
    private javax.swing.JPanel jPanelCOMPort;
    private javax.swing.JPanel jPanelFrame;
    private javax.swing.JPanel jPanelMotionControl;
    // End of variables declaration//GEN-END:variables
}
